Feat: keyword param char-bag for trim functions
vindarel/cl-str pull request #86
Opened 2023-01-23 19:44 UTC by kilianmh

- add keyword parameter `char-bag` to `trim`, `trim-right`, `trim-left`
- char-bag can be a sequence (e.g. list or string)
- char-bag defaults to `*whitespaces*`

- update tests for trim functions
- update documentation with examples

Is the parameter name `char-bag` appropriate? And do you like the documentation (same in docstring and readme)?

2023-01-24 14:41 UTC, vindarel requested changes

2023-01-24 14:41 UTC, vindarel commented on str.lisp
> +  "Removes all characters in `char-bag` (default: whitespaces) at the end of `s`.
beginning

2023-01-24 14:41 UTC, vindarel commented on str.lisp
> +   Example: (trim \"abrstcd\" :char-bag (concat \"a\" \"d\")) ;; => \"brstc\""
Did you remove the example with whitespaces? Please keep it, have both.

2023-01-24 14:48 UTC, vindarel commented
Hi, I like the feature, that's a great addition.

Re naming: is "char-bag" a usual name for this? If it's used in other libraries of other languages, then why not re-use it. If not, let's find a shorter name? (no good idea… simply "chars" ? I'll welcome the opinion of native english speakers, if char-bag is the best self-explanatory, so be it)

I think the examples (in the readme and the docstrings, yeah it's the same, we need to copy-paste one time) could be more straightforward by using strange letters around a common word, like "(trim "xyfooxy" :char-bag "xy"), but that's a nitpick.

2023-01-24 20:13 UTC, kilianmh commented
The change requested should be done.

I chose `char-bag` because
1. in the CL function `string-trim` its character-bag
2. in cl-str `char` is more used in parameters

`chars` is a straight forward short alternative. In the meantime the name `char-set` came to my mind. It's same length, however _character set_ is commonly used compared to _character bag_.

2023-01-25 16:38 UTC, vindarel commented
It's even char-bag for me:

```lisp
(defun string-trim (char-bag string)
  (generic-string-trim char-bag string t t))
```

looks good then.

A bit busy, will double check tomorrow.

2023-01-27 15:36 UTC, merged

2023-01-27 15:36 UTC, vindarel commented
Thanks!